### ISSUE TITLE
BUG: vfspak_seek warning on map change

### ISSUE THREAD

**Issue by dsvensson** [QW-Group/ezquake-source#880]
mvdsv-sync merge introduced the following warning:

![image](https://github.com/QW-Group/ezquake-source/assets/302027/a50c99da-a7c0-4e4f-a7fc-be37e0a46cd0)

Most likely related to [this commit](https://github.com/QW-Group/mvdsv/commit/1765473df456c147c12881739ffbc452e9bb3728) in mvdsv.

Either an incorrect seek, or an incorrect sanity check. No visible side-effects other than message.

**Comment by ciscon** [comment]
think this may have also been fixed by https://github.com/QW-Group/ezquake-source/pull/891 ?

**Comment by BLooD-DoG** [comment]
FYI I'm still seeing this on changing to e1m2. Not dm2/dm3/schloss/aero/ztn though

**Comment by dsvensson** [comment]
Looks like this commit wasn't picked over during the sync:

https://github.com/QW-Group/mvdsv/commit/1765473df456c147c12881739ffbc452e9bb3728
